"""
ChromaDB-backed semantic retrieval for AI-OS.

Replaces the keyword scorer in local_files.py with dense vector search
using Ollama nomic-embed-text embeddings. The public interface is
identical to local_files.retrieve_relevant_documents so callers need
no changes when switching backends via RETRIEVAL_BACKEND=chroma.

Design decisions:
- Embeddings are generated by calling the Ollama HTTP API directly
  (stdlib urllib only) rather than via chromadb's OllamaEmbeddingFunction
  utility, which changes import paths across chromadb versions.
- chromadb is imported lazily inside functions so that this module can
  be imported in any environment — including CI where chromadb may not
  be installed. Missing chromadb triggers the fallback, not an ImportError.
- All documents from all data paths share one ChromaDB collection,
  differentiated by a `data_root` metadata field. Retrieval filters to
  the requested root so Director OS and Brand OS never see each other's
  evidence.

Prerequisites:
    ollama pull nomic-embed-text
    python scripts/ingest_local_data.py

Fallback behaviour:
    Any failure — missing index, Ollama unreachable, chromadb not installed —
    falls through to the keyword scorer. The system degrades gracefully.
"""
from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from pathlib import Path

from packages.shared.retrieval.local_files import _resolve_allowed_data_path
from packages.shared.schemas.director_os import EvidenceItem

logger = logging.getLogger(__name__)

# Location of the persisted ChromaDB index. Added to .gitignore because
# the index is a derived artefact — rebuilt from source data via ingest_local_data.py.
CHROMA_DB_PATH = str((Path("data") / "chroma").resolve())
COLLECTION_NAME = "ai-os-docs"

# Embedding model pulled via: ollama pull nomic-embed-text
# nomic-embed-text is 274M, fast, and well-suited for short prose documents.
EMBEDDING_MODEL = "nomic-embed-text"

# Module-level singleton. ChromaDB's PersistentClient opens a SQLite
# connection and acquires a WAL file handle on construction. Re-creating it
# on every retrieve call causes repeated open/close cycles that serialize
# through the SQLite WAL lock under concurrent requests. One client per
# process is sufficient — the collection is read-only at query time.
_chroma_client: object | None = None


def retrieve_relevant_documents(
    base_path: str,
    query: str | None,
    limit: int,
) -> list[EvidenceItem]:
    """
    Semantic retrieval via ChromaDB + Ollama embeddings.

    Falls back to keyword retrieval (local_files) on any error so that
    the system stays functional before the first ingest run and in
    environments where Ollama is offline.
    """
    try:
        return _chroma_retrieve(base_path, query or "", limit)
    except Exception as exc:
        logger.warning(
            "ChromaDB retrieval failed — falling back to keyword retrieval. "
            "Reason: %s. Run 'python scripts/ingest_local_data.py' to build the index.",
            exc,
        )
        from packages.shared.retrieval.local_files import (
            retrieve_relevant_documents as _keyword,
        )
        return _keyword(base_path, query, limit)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_chroma_client() -> object:
    """Return the module-level ChromaDB client, initializing it on first use."""
    global _chroma_client
    if _chroma_client is None:
        try:
            import chromadb  # noqa: PLC0415
        except ImportError as exc:
            raise RuntimeError(
                "chromadb is not installed. "
                "Run: pip install 'chromadb>=0.5.0,<1.0.0'"
            ) from exc
        _chroma_client = chromadb.PersistentClient(path=CHROMA_DB_PATH)
    return _chroma_client


def _chroma_retrieve(base_path: str, query: str, limit: int) -> list[EvidenceItem]:
    """
    Core ChromaDB query path. Raises on any error so the public wrapper
    can decide whether to fall back or propagate.
    """
    chroma_path = Path(CHROMA_DB_PATH)
    if not chroma_path.exists():
        raise FileNotFoundError(
            f"ChromaDB index not found at '{chroma_path}'. "
            "Run: python scripts/ingest_local_data.py"
        )

    root = _resolve_allowed_data_path(base_path)
    ollama_url = os.getenv("OLLAMA_URL", "http://127.0.0.1:11434")

    # Generate the query embedding from Ollama before opening the DB client
    # so a network failure surfaces immediately rather than after the DB opens.
    query_embedding = _embed(query or "general project update", EMBEDDING_MODEL, ollama_url)

    client = _get_chroma_client()
    try:
        collection = client.get_collection(name=COLLECTION_NAME)
    except Exception as exc:
        raise RuntimeError(
            f"Collection '{COLLECTION_NAME}' not found in index at '{chroma_path}'. "
            "Run: python scripts/ingest_local_data.py"
        ) from exc

    doc_count = collection.count()
    if doc_count == 0:
        raise RuntimeError(
            f"Collection '{COLLECTION_NAME}' is empty. "
            "Run: python scripts/ingest_local_data.py"
        )

    # Per-path staleness: the collection may have docs for other data roots
    # but none for this path if it was never ingested. Detect this before
    # querying so the operator gets a clear message rather than silent keyword
    # fallback with no indication the semantic index was bypassed.
    path_check = collection.get(
        where={"data_root": str(root)}, limit=1, include=["documents"]
    )
    if not path_check["ids"]:
        raise RuntimeError(
            f"ChromaDB index has no documents for data path '{root}'. "
            "This path was not ingested. "
            "Run: python scripts/ingest_local_data.py"
        )

    # Filter to only the requested data root so Director OS retrieval
    # stays within projects/ and Brand OS retrieval stays within brand/.
    # The data_root stored during ingestion is the resolved absolute path
    # so it matches regardless of how the caller passes the relative path.
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=min(limit, doc_count),
        where={"data_root": str(root)},
        include=["documents", "metadatas", "distances"],
    )

    return _parse_results(results)


def _embed(text: str, model: str, ollama_url: str) -> list[float]:
    """
    Call the Ollama /api/embeddings endpoint and return the float vector.

    Uses stdlib urllib so no extra dependency is needed beyond Ollama itself.
    Raises urllib.error.URLError when Ollama is unreachable — the caller
    (retrieve_relevant_documents) treats this as a cue to fall back.
    """
    payload = json.dumps({"model": model, "prompt": text}).encode("utf-8")
    req = urllib.request.Request(
        f"{ollama_url}/api/embeddings",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["embedding"]


def is_index_ready() -> bool:
    """Return True if the ChromaDB index directory exists and contains files."""
    path = Path(CHROMA_DB_PATH)
    return path.exists() and any(path.iterdir())


def _parse_results(results: dict) -> list[EvidenceItem]:
    """
    Convert raw ChromaDB query results to EvidenceItem objects.

    results["documents"] and results["metadatas"] are each a list-of-lists
    because ChromaDB supports batched queries. We always send a single query
    so we take index [0].
    """
    documents: list[str] = results.get("documents", [[]])[0]
    metadatas: list[dict] = results.get("metadatas", [[]])[0]

    evidence: list[EvidenceItem] = []
    for doc, meta in zip(documents, metadatas):
        if not doc:
            continue
        raw_path = meta.get("relative_path", "unknown")
        evidence.append(
            EvidenceItem(
                # Keep the full relative path (not just the basename) so
                # citations match the local_files backend exactly — two files
                # with the same name in different folders must stay
                # distinguishable in the evidence a caller cites back.
                source=raw_path,
                line_number=int(meta.get("line_number", 0)),
                title=meta.get("title", ""),
                excerpt=doc[:280],
            )
        )
    return evidence
